### ISSUE TITLE
Can't run the server

### ISSUE THREAD

**Issue by justinjk007** [rm5248/Java-RMI-Example#3]
I compiled everything from the root using `mvn package`, I ran `compile` first, but then thought may be I need to package for the modules to work. Then i tried running it. I have  `rmiregistry` running like this
```
justin@justin-Precision-3520 14:16:42 ~/Repos/Java-RMI-Example/RMIServer 
$ rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false
```

But trying to run the Server fails like this saying can't find the Interface classes. I am using latest maven btw.

```
justin@justin-Precision-3520 14:13:58 ~/Repos/Java-RMI-Example/RMIServer/target/classes 
$ pwd
/home/justin/Repos/Java-RMI-Example/RMIServer/target/classes

justin@justin-Precision-3520 14:15:15 ~/Repos/Java-RMI-Example/RMIServer/target/classes 
$ java -Djava.rmi.server.useCodebaseOnly=false -Djava.rmi.server.codebase=file:/home/justin/Repos/Java-RMI-Example/RMIServer/target/classes/com/rm5248/rmiserver/  com.rm5248.rmiserver.RMIServerMain
Exception in thread "main" java.lang.NoClassDefFoundError: com/rm5248/rmiinterfaces/PrintingInterface
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.rm5248.rmiserver.RMIServerMain.main(RMIServerMain.java:28)
Caused by: java.lang.ClassNotFoundException: com.rm5248.rmiinterfaces.PrintingInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

**Comment by rm5248** [comment]
Looking at your call to 'java', instead of 

`java -Djava.rmi.server.useCodebaseOnly=false -Djava.rmi.server.codebase=file:/home/justin/Repos/Java-RMI-Example/RMIServer/target/classes/com/rm5248/rmiserver/  com.rm5248.rmiserver.RMIServerMain`
 it should probably be 
`java -Djava.rmi.server.useCodebaseOnly=false -Djava.rmi.server.codebase=file:/home/justin/Repos/Java-RMI-Example/RMIServer/target/classes  com.rm5248.rmiserver.RMIServerMain`
instead.

Otherwise, it may be `java -Djava.rmi.server.useCodebaseOnly=false -Djava.rmi.server.codebase=file:/home/justin/Repos/Java-RMI-Example/RMIInterfaces/target/classes  com.rm5248.rmiserver.RMIServerMain` instead; I don't remember exactly which classes folder you need to actually run it.  At least one of your problems is that you have specified a longer path than should happen; since Java assumes that your classes will be structured in a certain order inside of files, you're breaking that by passing everything after `classes/` to Java.

**Comment by justinjk007** [comment]
both the suggestions are failing the same way my command failed :cry:

**Comment by rm5248** [comment]
Well, unfortunately I have no other ideas.  I don't use RMI at all, this was just an experiment to see how it worked.

If you do figure out what the problem is though, feel free to send a PR with documentation on how to fix it.

**Comment by justinjk007** [comment]
OMGGGG I give up. I finally got the server running. It was failing because I had to install the dependencies using `mvn install` for the server to get the interface class. After that I can't seem to get the client running. I modified the `pom.xml` under the client to pass in command line arguments so I can just run it using `mvn exec:java` but nope. Not working.

Also the examples I see only require the Server to be given the special all access permissions but in your example you need it for the client. Welp I tried to run the client and server with all permissions nope.


GG.
